defmodule Storybox.Repo.Migrations.WorldIdentity do
  @moduledoc """
  Gives the World Component first-class identity: a required `name` and a
  required, per-story-unique `slug` handle.

  Hand-authored (rather than purely autogenerated) because backfill SQL must be
  interleaved with the schema changes: `name` and `slug` are added nullable,
  backfilled for any existing rows, and only then made NOT NULL. The matching
  resource snapshot is autogenerated.
  """

  use Ecto.Migration

  def up do
    # 1. Add name + slug (nullable first so existing rows can be backfilled).
    alter table(:worlds) do
      add :name, :text
      add :slug, :text
    end

    # 2. Backfill the seeded external world's identity. Dead path in practice —
    #    seed rows are recreated with authored name/slug.
    execute "UPDATE worlds SET name = 'External World' WHERE name IS NULL"
    execute "UPDATE worlds SET slug = 'external_world' WHERE slug IS NULL"

    # 3. Enforce NOT NULL now that every row has both.
    alter table(:worlds) do
      modify :name, :text, null: false
      modify :slug, :text, null: false
    end

    # 4. Unique slug per story.
    create unique_index(:worlds, [:story_id, :slug], name: "worlds_unique_slug_per_story_index")
  end

  def down do
    drop_if_exists unique_index(:worlds, [:story_id, :slug],
                     name: "worlds_unique_slug_per_story_index"
                   )

    alter table(:worlds) do
      remove :slug
      remove :name
    end
  end
end
