defmodule Storybox.Repo.Migrations.AddSegmentSceneAndTaskTargetScene do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      add :target_scene_id, :uuid
    end

    create index(:tasks, [:target_scene_id])

    alter table(:segments) do
      add :scene_id,
          references(:scenes,
            column: :id,
            name: "segments_scene_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:segments, [:view_version_id, :scene_id], where: "scene_id IS NOT NULL")
  end

  def down do
    drop constraint(:segments, "segments_scene_id_fkey")

    drop_if_exists index(:segments, [:view_version_id, :scene_id])

    alter table(:segments) do
      remove :scene_id
    end

    drop_if_exists index(:tasks, [:target_scene_id])

    alter table(:tasks) do
      remove :target_scene_id
    end
  end
end
