defmodule Storybox.Repo.Migrations.OrderFreeCuts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:story_script_view_versions) do
      remove :source_treatment_view_version_id
    end
  end

  def down do
    alter table(:story_script_view_versions) do
      add :source_treatment_view_version_id, :uuid, null: false
    end
  end
end
