defmodule Storybox.Repo.Migrations.RefactorScriptPiece do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Existing rows reference script_view_id which is being dropped; the new
    # scene_id column is NOT NULL with no sensible backfill. Seed rebuilds.
    execute "TRUNCATE TABLE script_pieces"

    alter table(:script_pieces) do
      remove :script_view_id
      remove :upstream_status
      add :source_sequence_piece_id, :uuid
      add :source_version_at_creation, :bigint

      add :scene_id,
          references(:scenes,
            column: :id,
            name: "script_pieces_scene_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:script_pieces, "script_pieces_scene_id_fkey")

    alter table(:script_pieces) do
      remove :scene_id
      remove :source_version_at_creation
      remove :source_sequence_piece_id
      add :upstream_status, :text, null: false, default: "current"

      add :script_view_id,
          references(:script_views,
            column: :id,
            name: "script_pieces_script_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
