defmodule Storybox.Repo.Migrations.DropSceneMotif do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:scenes) do
      remove :motif
    end
  end

  def down do
    alter table(:scenes) do
      add :motif, :text
    end
  end
end
