defmodule Storybox.Repo.Migrations.SceneComponent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  NOTE: This migration was originally written against a DB that had already had
  the rename_piece_version_vocabulary migration applied (sequence_pieces →
  treatment_views, etc.). On a fresh DB the rename runs AFTER this file's
  timestamp, so all operations are guarded with IF EXISTS / table-name detection
  to work correctly in both orderings.
  """

  use Ecto.Migration

  def up do
    # FK renames and treatment_view_scenes creation — only when treatment_views
    # already exists (i.e. the rename migration ran first on this DB).
    execute """
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'treatment_views'
      ) THEN
        ALTER TABLE treatment_views
          DROP CONSTRAINT IF EXISTS sequence_pieces_story_id_fkey;
        ALTER TABLE treatment_views
          ADD CONSTRAINT treatment_views_story_id_fkey
          FOREIGN KEY (story_id) REFERENCES stories(id);

        ALTER TABLE treatment_pieces
          DROP CONSTRAINT IF EXISTS sequence_versions_sequence_piece_id_fkey;
        ALTER TABLE treatment_pieces
          ADD CONSTRAINT treatment_pieces_treatment_view_id_fkey
          FOREIGN KEY (treatment_view_id) REFERENCES treatment_views(id);
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'synopsis_views'
      ) THEN
        ALTER TABLE synopsis_views
          DROP CONSTRAINT IF EXISTS synopsis_versions_story_id_fkey;
        ALTER TABLE synopsis_views
          ADD CONSTRAINT synopsis_views_story_id_fkey
          FOREIGN KEY (story_id) REFERENCES stories(id);
      END IF;
    END
    $$
    """

    # Create scenes table (must exist before treatment_view_scenes and script_views.scene_id)
    create table(:scenes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "scenes_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    # Create treatment_view_scenes join table — only when treatment_views exists.
    execute """
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'treatment_views'
      ) THEN
        CREATE TABLE treatment_view_scenes (
          id          uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
          position    bigint      NOT NULL,
          inserted_at timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
          updated_at  timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
          treatment_view_id uuid NOT NULL
            REFERENCES treatment_views(id)
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED,
          scene_id    uuid NOT NULL
            REFERENCES scenes(id)
            ON DELETE RESTRICT
            DEFERRABLE INITIALLY DEFERRED
        );
      END IF;
    END
    $$
    """

    # The script_views table may be named scene_pieces (pre-rename) or script_views
    # (post-rename). Detect which name is in use and add scene_id accordingly.
    execute """
    DO $$
    DECLARE
      _tbl text;
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'script_views'
      ) THEN
        _tbl := 'script_views';
      ELSE
        _tbl := 'scene_pieces';
      END IF;

      EXECUTE format(
        'ALTER TABLE %I ADD COLUMN IF NOT EXISTS scene_id uuid
           REFERENCES scenes(id)
           ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED',
        _tbl
      );
    END
    $$
    """

    # Data migration: create a Scene + TreatmentViewScene for each existing row.
    # Only runs when treatment_views exists (pre-existing DB with data).
    execute """
    DO $$
    DECLARE
      _sv_tbl text;
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'treatment_views'
      ) THEN
        RETURN;
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'script_views'
      ) THEN
        _sv_tbl := 'script_views';
      ELSE
        _sv_tbl := 'scene_pieces';
      END IF;

      CREATE TEMP TABLE IF NOT EXISTS _scene_migrations (
        script_view_id    uuid NOT NULL,
        scene_id          uuid NOT NULL,
        treatment_view_id uuid NOT NULL,
        position          bigint NOT NULL
      );

      EXECUTE format(
        'INSERT INTO _scene_migrations (script_view_id, scene_id, treatment_view_id, position)
         SELECT sv.id, gen_random_uuid(), sv.treatment_view_id, sv.position
         FROM %I sv
         WHERE sv.treatment_view_id IS NOT NULL',
        _sv_tbl
      );

      INSERT INTO scenes (id, title, story_id, inserted_at, updated_at)
      SELECT sm.scene_id, sv.title, tv.story_id,
             (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
      FROM _scene_migrations sm
      JOIN script_views sv ON sv.id = sm.script_view_id
      JOIN treatment_views tv ON tv.id = sm.treatment_view_id;

      EXECUTE format(
        'UPDATE %I SET scene_id = sm.scene_id
         FROM _scene_migrations sm
         WHERE %I.id = sm.script_view_id',
        _sv_tbl, _sv_tbl
      );

      INSERT INTO treatment_view_scenes (id, treatment_view_id, scene_id, position, inserted_at, updated_at)
      SELECT gen_random_uuid(), sm.treatment_view_id, sm.scene_id, sm.position,
             (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
      FROM _scene_migrations sm;

      DROP TABLE IF EXISTS _scene_migrations;
    END
    $$
    """

    # Enforce NOT NULL on scene_id (in whichever table it lives in right now)
    execute """
    DO $$
    DECLARE
      _tbl text;
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'script_views'
      ) THEN
        _tbl := 'script_views';
      ELSE
        _tbl := 'scene_pieces';
      END IF;

      EXECUTE format(
        'ALTER TABLE %I ALTER COLUMN scene_id SET NOT NULL',
        _tbl
      );
    END
    $$
    """

    # Remove old columns and FK from script_views / scene_pieces
    execute """
    DO $$
    DECLARE
      _tbl text;
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'script_views'
      ) THEN
        _tbl := 'script_views';
      ELSE
        _tbl := 'scene_pieces';
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = _tbl AND column_name = 'treatment_view_id'
      ) THEN
        EXECUTE format('ALTER TABLE %I DROP COLUMN treatment_view_id', _tbl);
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = _tbl AND column_name = 'sequence_piece_id'
      ) THEN
        EXECUTE format('ALTER TABLE %I DROP COLUMN sequence_piece_id', _tbl);
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = _tbl AND column_name = 'position'
      ) THEN
        EXECUTE format('ALTER TABLE %I DROP COLUMN position', _tbl);
      END IF;
    END
    $$
    """

    # Update script_pieces FK constraint name
    execute """
    DO $$
    DECLARE
      _sp_tbl text;
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'script_pieces'
      ) THEN
        _sp_tbl := 'script_pieces';
      ELSE
        _sp_tbl := 'scene_versions';
      END IF;

      IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public' AND table_name = _sp_tbl
          AND constraint_name = 'scene_versions_scene_piece_id_fkey'
      ) THEN
        EXECUTE format(
          'ALTER TABLE %I DROP CONSTRAINT scene_versions_scene_piece_id_fkey',
          _sp_tbl
        );
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public' AND table_name = _sp_tbl
          AND constraint_name = 'script_pieces_script_view_id_fkey'
      ) THEN
        IF EXISTS (
          SELECT 1 FROM information_schema.tables
          WHERE table_schema = 'public' AND table_name = 'script_views'
        ) THEN
          EXECUTE format(
            'ALTER TABLE %I ADD CONSTRAINT script_pieces_script_view_id_fkey
             FOREIGN KEY (script_view_id) REFERENCES script_views(id)',
            _sp_tbl
          );
        ELSE
          EXECUTE format(
            'ALTER TABLE %I ADD CONSTRAINT script_pieces_script_view_id_fkey
             FOREIGN KEY (scene_piece_id) REFERENCES scene_pieces(id)',
            _sp_tbl
          );
        END IF;
      END IF;
    END
    $$
    """
  end

  def down do
    drop constraint(:script_pieces, "script_pieces_script_view_id_fkey")

    alter table(:script_pieces) do
      modify :script_view_id,
             references(:script_views,
               column: :id,
               name: "scene_versions_scene_piece_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:script_views) do
      remove :scene_id
      add :position, :bigint, null: false, default: 1
      add :treatment_view_id, :uuid, null: true
    end

    drop constraint(:treatment_view_scenes, "treatment_view_scenes_treatment_view_id_fkey")
    drop constraint(:treatment_view_scenes, "treatment_view_scenes_scene_id_fkey")
    drop table(:treatment_view_scenes)

    drop constraint(:scenes, "scenes_story_id_fkey")
    drop table(:scenes)

    drop constraint(:synopsis_views, "synopsis_views_story_id_fkey")

    alter table(:synopsis_views) do
      modify :story_id,
             references(:stories,
               column: :id,
               name: "synopsis_versions_story_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:treatment_pieces, "treatment_pieces_treatment_view_id_fkey")

    alter table(:treatment_pieces) do
      modify :treatment_view_id,
             references(:treatment_views,
               column: :id,
               name: "sequence_versions_sequence_piece_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:treatment_views, "treatment_views_story_id_fkey")

    alter table(:treatment_views) do
      modify :story_id,
             references(:stories,
               column: :id,
               name: "sequence_pieces_story_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
