defmodule Storybox.Repo.Migrations.AddCrossLayerVvRefs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:story_script_view_versions) do
      add :treatment_view_version_id,
          references(:treatment_view_versions,
            column: :id,
            name: "story_script_view_versions_treatment_view_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:treatment_view_versions) do
      add :synopsis_view_version_id,
          references(:synopsis_view_versions,
            column: :id,
            name: "treatment_view_versions_synopsis_view_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :treatment_view_versions,
           "treatment_view_versions_synopsis_view_version_id_fkey"
         )

    alter table(:treatment_view_versions) do
      remove :synopsis_view_version_id
    end

    drop constraint(
           :story_script_view_versions,
           "story_script_view_versions_treatment_view_version_id_fkey"
         )

    alter table(:story_script_view_versions) do
      remove :treatment_view_version_id
    end
  end
end
