defmodule Storybox.Repo.Migrations.SceneComponent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Rename stale FK constraint names left over from the table rename migration
    drop constraint(:treatment_views, "sequence_pieces_story_id_fkey")

    alter table(:treatment_views) do
      modify :story_id,
             references(:stories,
               column: :id,
               name: "treatment_views_story_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:treatment_pieces, "sequence_versions_sequence_piece_id_fkey")

    alter table(:treatment_pieces) do
      modify :treatment_view_id,
             references(:treatment_views,
               column: :id,
               name: "treatment_pieces_treatment_view_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:synopsis_views, "synopsis_versions_story_id_fkey")

    alter table(:synopsis_views) do
      modify :story_id,
             references(:stories,
               column: :id,
               name: "synopsis_views_story_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    # Create scenes table (must exist before treatment_view_scenes and script_views.scene_id)
    create table(:scenes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :slug, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "scenes_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    # Create treatment_view_scenes join table
    create table(:treatment_view_scenes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :treatment_view_id,
          references(:treatment_views,
            column: :id,
            name: "treatment_view_scenes_treatment_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :scene_id,
          references(:scenes,
            column: :id,
            name: "treatment_view_scenes_scene_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    # Add scene_id as nullable first — populated in the data migration below
    alter table(:script_views) do
      add :scene_id,
          references(:scenes,
            column: :id,
            name: "script_views_scene_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: true
    end

    # Data migration: create a Scene + TreatmentViewScene for each existing ScriptView
    execute """
    CREATE TEMP TABLE _scene_migrations (
      script_view_id uuid NOT NULL,
      scene_id       uuid NOT NULL,
      treatment_view_id uuid NOT NULL,
      position       bigint NOT NULL
    )
    """

    execute """
    INSERT INTO _scene_migrations (script_view_id, scene_id, treatment_view_id, position)
    SELECT sv.id, gen_random_uuid(), sv.treatment_view_id, sv.position
    FROM script_views sv
    WHERE sv.treatment_view_id IS NOT NULL
    """

    execute """
    INSERT INTO scenes (id, title, story_id, inserted_at, updated_at)
    SELECT sm.scene_id, sv.title, tv.story_id,
           (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
    FROM _scene_migrations sm
    JOIN script_views sv ON sv.id = sm.script_view_id
    JOIN treatment_views tv ON tv.id = sm.treatment_view_id
    """

    execute """
    UPDATE script_views
    SET scene_id = sm.scene_id
    FROM _scene_migrations sm
    WHERE script_views.id = sm.script_view_id
    """

    execute """
    INSERT INTO treatment_view_scenes (id, treatment_view_id, scene_id, position, inserted_at, updated_at)
    SELECT gen_random_uuid(), sm.treatment_view_id, sm.scene_id, sm.position,
           (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc')
    FROM _scene_migrations sm
    """

    execute "DROP TABLE _scene_migrations"

    # Enforce NOT NULL and drop old columns from script_views
    execute "ALTER TABLE script_views ALTER COLUMN scene_id SET NOT NULL"

    alter table(:script_views) do
      remove :treatment_view_id
      remove :position
    end

    # Update script_pieces FK constraint name to match new table vocabulary
    drop constraint(:script_pieces, "scene_versions_scene_piece_id_fkey")

    alter table(:script_pieces) do
      modify :script_view_id,
             references(:script_views,
               column: :id,
               name: "script_pieces_script_view_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:script_pieces, "script_pieces_script_view_id_fkey")

    alter table(:script_pieces) do
      modify :script_view_id,
             references(:script_views,
               column: :id,
               name: "scene_versions_scene_piece_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:script_views) do
      remove :scene_id
      add :position, :bigint, null: false, default: 1
      add :treatment_view_id, :uuid, null: true
    end

    drop constraint(:treatment_view_scenes, "treatment_view_scenes_treatment_view_id_fkey")
    drop constraint(:treatment_view_scenes, "treatment_view_scenes_scene_id_fkey")
    drop table(:treatment_view_scenes)

    drop constraint(:scenes, "scenes_story_id_fkey")
    drop table(:scenes)

    drop constraint(:synopsis_views, "synopsis_views_story_id_fkey")

    alter table(:synopsis_views) do
      modify :story_id,
             references(:stories,
               column: :id,
               name: "synopsis_versions_story_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:treatment_pieces, "treatment_pieces_treatment_view_id_fkey")

    alter table(:treatment_pieces) do
      modify :treatment_view_id,
             references(:treatment_views,
               column: :id,
               name: "sequence_versions_sequence_piece_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:treatment_views, "treatment_views_story_id_fkey")

    alter table(:treatment_views) do
      modify :story_id,
             references(:stories,
               column: :id,
               name: "sequence_pieces_story_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
