defmodule Storybox.Repo.Migrations.SceneSlugAndMotif do
  @moduledoc """
  Replaces Scene's required `title` with an optional `motif`, makes `slug`
  required and unique per story.

  Hand-authored (rather than purely autogenerated) because backfill SQL must be
  interleaved with the schema changes: `motif` is backfilled from the retired
  `title`, and any row missing a `slug` is backfilled before the NOT NULL
  constraint is applied. The matching resource snapshot is autogenerated.
  """

  use Ecto.Migration

  def up do
    # 1. Add motif (nullable).
    alter table(:scenes) do
      add :motif, :text
    end

    # 2. Backfill motif from the retired title.
    execute "UPDATE scenes SET motif = title WHERE motif IS NULL"

    # 3. Backfill slug for any row missing one, using underscores to match the
    #    existing seed slug convention (e.g. ext_ruins_kestrel). Dead path in
    #    practice — seed rows already carry slugs.
    execute "UPDATE scenes SET slug = regexp_replace(lower(title), '[^a-z0-9]+', '_', 'g') WHERE slug IS NULL"

    # 4. Enforce slug NOT NULL now that every row has one.
    alter table(:scenes) do
      modify :slug, :text, null: false
    end

    # 5. Drop the retired title column.
    alter table(:scenes) do
      remove :title
    end

    # 6. Unique slug per story.
    create unique_index(:scenes, [:story_id, :slug], name: "scenes_unique_slug_per_story_index")
  end

  def down do
    drop_if_exists unique_index(:scenes, [:story_id, :slug],
                     name: "scenes_unique_slug_per_story_index"
                   )

    # Re-add title (nullable first so it can be backfilled).
    alter table(:scenes) do
      add :title, :text
    end

    # Backfill title from motif, falling back to slug for motif-less scenes
    # (slug is NOT NULL at this point, so title is always populated).
    execute "UPDATE scenes SET title = COALESCE(motif, slug) WHERE title IS NULL"

    # Restore the original constraints: title NOT NULL, slug nullable.
    alter table(:scenes) do
      modify :title, :text, null: false
      modify :slug, :text, null: true
      remove :motif
    end
  end
end
