defmodule Storybox.Repo.Migrations.AddThroughlineHarness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:throughline_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "throughline_views_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:throughline_views, [:story_id],
             name: "throughline_views_unique_story_index"
           )

    create table(:throughline_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :throughline_view_id,
          references(:throughline_views,
            column: :id,
            name: "throughline_view_versions_throughline_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:throughline_view_versions, [:throughline_view_id, :version_number],
             name: "throughline_view_versions_unique_version_per_view_index"
           )

    create table(:throughline_pieces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_uri, :text, null: false
      add :version_number, :bigint, null: false
      add :weights, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "throughline_pieces_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :character_id,
          references(:characters,
            column: :id,
            name: "throughline_pieces_character_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:throughline_pieces, "throughline_pieces_story_id_fkey")

    drop constraint(:throughline_pieces, "throughline_pieces_character_id_fkey")

    drop table(:throughline_pieces)

    drop_if_exists unique_index(
                     :throughline_view_versions,
                     [:throughline_view_id, :version_number],
                     name: "throughline_view_versions_unique_version_per_view_index"
                   )

    drop constraint(
           :throughline_view_versions,
           "throughline_view_versions_throughline_view_id_fkey"
         )

    drop table(:throughline_view_versions)

    drop_if_exists unique_index(:throughline_views, [:story_id],
                     name: "throughline_views_unique_story_index"
                   )

    drop constraint(:throughline_views, "throughline_views_story_id_fkey")

    drop table(:throughline_views)
  end
end
