defmodule Storybox.Repo.Migrations.AddSequenceThinConnector do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sequences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "sequences_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:sequences, [:story_id, :slug],
             name: "sequences_unique_slug_per_story_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sequences, [:story_id, :slug],
                     name: "sequences_unique_slug_per_story_index"
                   )

    drop constraint(:sequences, "sequences_story_id_fkey")

    drop table(:sequences)
  end
end
