defmodule Storybox.Repo.Migrations.AddThroughlineVvRefToSynopsisViewVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:synopsis_view_versions) do
      add :throughline_view_version_id,
          references(:throughline_view_versions,
            column: :id,
            name: "synopsis_view_versions_throughline_view_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(
           :synopsis_view_versions,
           "synopsis_view_versions_throughline_view_version_id_fkey"
         )

    alter table(:synopsis_view_versions) do
      remove :throughline_view_version_id
    end
  end
end
