defmodule Storybox.Repo.Migrations.AddSequenceResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sequence_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_uri, :text, null: false
      add :version_number, :bigint, null: false
      add :weights, :map, default: %{}
      add :upstream_status, :text, null: false, default: "current"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sequence_piece_id, :uuid, null: false
    end

    create table(:sequence_pieces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sequence_versions) do
      modify :sequence_piece_id,
             references(:sequence_pieces,
               column: :id,
               name: "sequence_versions_sequence_piece_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sequence_pieces) do
      add :title, :text, null: false
      add :act, :text
      add :position, :bigint, null: false
      add :approved_version_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "sequence_pieces_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:sequence_pieces, "sequence_pieces_story_id_fkey")

    alter table(:sequence_pieces) do
      remove :story_id
      remove :updated_at
      remove :inserted_at
      remove :approved_version_id
      remove :position
      remove :act
      remove :title
    end

    drop constraint(:sequence_versions, "sequence_versions_sequence_piece_id_fkey")

    alter table(:sequence_versions) do
      modify :sequence_piece_id, :uuid
    end

    drop table(:sequence_pieces)

    drop table(:sequence_versions)
  end
end
