defmodule Storybox.Repo.Migrations.ScriptViewVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:script_views) do
      remove :updated_at
      remove :approved_version_id
      remove :title
    end

    # Dev DB may have multiple rows per scene from the old create action.
    # Keep only the most recently inserted row per scene before enforcing uniqueness.
    execute """
    DELETE FROM script_views
    WHERE id NOT IN (
      SELECT DISTINCT ON (scene_id) id
      FROM script_views
      ORDER BY scene_id, inserted_at DESC
    )
    """

    create unique_index(:script_views, [:scene_id], name: "script_views_unique_scene_index")

    create table(:script_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :script_view_id,
          references(:script_views,
            column: :id,
            name: "script_view_versions_script_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:script_view_versions, [:script_view_id, :version_number],
             name: "script_view_versions_unique_version_per_view_index"
           )
  end

  def down do
    drop_if_exists unique_index(:script_view_versions, [:script_view_id, :version_number],
                     name: "script_view_versions_unique_version_per_view_index"
                   )

    drop constraint(:script_view_versions, "script_view_versions_script_view_id_fkey")

    drop table(:script_view_versions)

    drop_if_exists unique_index(:script_views, [:scene_id],
                     name: "script_views_unique_scene_index"
                   )

    alter table(:script_views) do
      add :title, :text, null: false
      add :approved_version_id, :uuid

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end
end
