defmodule Storybox.Repo.Migrations.AddStorySpine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:story_spine_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_spine_id, :uuid, null: false
      add :sequence_id, :uuid, null: false
    end

    create index(:story_spine_entries, [:story_spine_id, :sequence_id])

    create table(:story_spines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:story_spine_entries) do
      modify :story_spine_id,
             references(:story_spines,
               column: :id,
               name: "story_spine_entries_story_spine_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "story_spine_entries_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:story_spine_entries, [:story_spine_id, :position],
             name: "story_spine_entries_unique_position_per_spine_index"
           )

    create unique_index(:story_spine_entries, [:story_spine_id, :sequence_id],
             name: "story_spine_entries_unique_sequence_per_spine_index"
           )

    alter table(:story_spines) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "story_spines_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:story_spines, [:story_id], name: "story_spines_unique_story_index")

    create table(:story_spine_vv_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_spine_view_version_id, :uuid, null: false
      add :sequence_id, :uuid, null: false
    end

    create index(:story_spine_vv_entries, [:story_spine_view_version_id, :sequence_id])

    create table(:story_spine_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:story_spine_vv_entries) do
      modify :story_spine_view_version_id,
             references(:story_spine_view_versions,
               column: :id,
               name: "story_spine_vv_entries_story_spine_view_version_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :sequence_id,
             references(:sequences,
               column: :id,
               name: "story_spine_vv_entries_sequence_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:story_spine_vv_entries, [:story_spine_view_version_id, :position],
             name: "story_spine_vv_entries_unique_position_per_vv_index"
           )

    create unique_index(:story_spine_vv_entries, [:story_spine_view_version_id, :sequence_id],
             name: "story_spine_vv_entries_unique_sequence_per_vv_index"
           )

    alter table(:story_spine_view_versions) do
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_spine_id,
          references(:story_spines,
            column: :id,
            name: "story_spine_view_versions_story_spine_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:story_spine_view_versions, [:story_spine_id, :version_number],
             name: "story_spine_view_versions_unique_version_per_spine_index"
           )
  end

  def down do
    drop_if_exists unique_index(:story_spine_view_versions, [:story_spine_id, :version_number],
                     name: "story_spine_view_versions_unique_version_per_spine_index"
                   )

    drop constraint(:story_spine_view_versions, "story_spine_view_versions_story_spine_id_fkey")

    alter table(:story_spine_view_versions) do
      remove :story_spine_id
      remove :inserted_at
      remove :version_number
    end

    drop_if_exists unique_index(
                     :story_spine_vv_entries,
                     [:story_spine_view_version_id, :sequence_id],
                     name: "story_spine_vv_entries_unique_sequence_per_vv_index"
                   )

    drop_if_exists unique_index(
                     :story_spine_vv_entries,
                     [:story_spine_view_version_id, :position],
                     name: "story_spine_vv_entries_unique_position_per_vv_index"
                   )

    drop constraint(
           :story_spine_vv_entries,
           "story_spine_vv_entries_story_spine_view_version_id_fkey"
         )

    drop constraint(:story_spine_vv_entries, "story_spine_vv_entries_sequence_id_fkey")

    alter table(:story_spine_vv_entries) do
      modify :sequence_id, :uuid
      modify :story_spine_view_version_id, :uuid
    end

    drop table(:story_spine_view_versions)

    drop_if_exists index(:story_spine_vv_entries, [:story_spine_view_version_id, :sequence_id])

    drop table(:story_spine_vv_entries)

    drop_if_exists unique_index(:story_spines, [:story_id],
                     name: "story_spines_unique_story_index"
                   )

    drop constraint(:story_spines, "story_spines_story_id_fkey")

    alter table(:story_spines) do
      remove :story_id
      remove :inserted_at
    end

    drop_if_exists unique_index(:story_spine_entries, [:story_spine_id, :sequence_id],
                     name: "story_spine_entries_unique_sequence_per_spine_index"
                   )

    drop_if_exists unique_index(:story_spine_entries, [:story_spine_id, :position],
                     name: "story_spine_entries_unique_position_per_spine_index"
                   )

    drop constraint(:story_spine_entries, "story_spine_entries_story_spine_id_fkey")

    drop constraint(:story_spine_entries, "story_spine_entries_sequence_id_fkey")

    alter table(:story_spine_entries) do
      modify :sequence_id, :uuid
      modify :story_spine_id, :uuid
    end

    drop table(:story_spines)

    drop_if_exists index(:story_spine_entries, [:story_spine_id, :sequence_id])

    drop table(:story_spine_entries)
  end
end
