defmodule Storybox.Repo.Migrations.AddSequencePiece do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists table(:treatment_pieces)

    create table(:sequence_pieces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_uri, :text, null: false
      add :version_number, :bigint, null: false
      add :weights, :map, default: %{}
      add :source_synopsis_piece_id, :uuid
      add :source_version_at_creation, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "sequence_pieces_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "sequence_pieces_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:sequence_pieces, "sequence_pieces_story_id_fkey")

    drop constraint(:sequence_pieces, "sequence_pieces_sequence_id_fkey")

    drop table(:sequence_pieces)
  end
end
