defmodule Storybox.Repo.Migrations.AddSegments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:segments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :view_version_id, :uuid, null: false
      add :view_version_type, :text, null: false
      add :position, :bigint, null: false
      add :pin_id, :uuid
      add :pin_type, :text
      add :pin_version_at_creation, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "segments_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:segments, [:view_version_id, :sequence_id], where: "sequence_id IS NOT NULL")

    create unique_index(:segments, [:view_version_id, :view_version_type, :position],
             name: "segments_unique_position_per_vv_index"
           )

    create constraint(:segments, :segments_pin_complete_or_empty,
             check: """
               (pin_id IS NULL AND pin_type IS NULL AND pin_version_at_creation IS NULL) OR (pin_id IS NOT NULL AND pin_type IS NOT NULL AND pin_version_at_creation IS NOT NULL)
             """
           )
  end

  def down do
    drop_if_exists constraint(:segments, :segments_pin_complete_or_empty)

    drop_if_exists unique_index(:segments, [:view_version_id, :view_version_type, :position],
                     name: "segments_unique_position_per_vv_index"
                   )

    drop constraint(:segments, "segments_sequence_id_fkey")

    drop_if_exists index(:segments, [:view_version_id, :sequence_id])

    drop table(:segments)
  end
end
