defmodule Storybox.Repo.Migrations.DropPieceProvenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sequence_pieces) do
      remove :source_version_at_creation
      remove :source_synopsis_piece_id
    end

    alter table(:script_pieces) do
      remove :source_version_at_creation
      remove :source_sequence_piece_id
    end
  end

  def down do
    alter table(:script_pieces) do
      add :source_sequence_piece_id, :uuid
      add :source_version_at_creation, :bigint
    end

    alter table(:sequence_pieces) do
      add :source_synopsis_piece_id, :uuid
      add :source_version_at_creation, :bigint
    end
  end
end
