defmodule Storybox.Repo.Migrations.AddSynopsisVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:synopsis_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_uri, :text, null: false
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "synopsis_versions_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:synopsis_versions, "synopsis_versions_story_id_fkey")

    drop table(:synopsis_versions)
  end
end
