defmodule Storybox.Repo.Migrations.AddTreatmentView do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:treatment_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "treatment_views_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:treatment_views, [:story_id], name: "treatment_views_unique_story_index")

    create table(:treatment_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :treatment_view_id,
          references(:treatment_views,
            column: :id,
            name: "treatment_view_versions_treatment_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:treatment_view_versions, [:treatment_view_id, :version_number],
             name: "treatment_view_versions_unique_version_per_view_index"
           )
  end

  def down do
    drop_if_exists unique_index(:treatment_view_versions, [:treatment_view_id, :version_number],
                     name: "treatment_view_versions_unique_version_per_view_index"
                   )

    drop constraint(:treatment_view_versions, "treatment_view_versions_treatment_view_id_fkey")

    drop table(:treatment_view_versions)

    drop_if_exists unique_index(:treatment_views, [:story_id],
                     name: "treatment_views_unique_story_index"
                   )

    drop constraint(:treatment_views, "treatment_views_story_id_fkey")

    drop table(:treatment_views)
  end
end
