defmodule Storybox.Repo.Migrations.DropThroughLinesFromStories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stories) do
      remove :through_lines
    end
  end

  def down do
    alter table(:stories) do
      add :through_lines, {:array, :text}
    end
  end
end
