defmodule Storybox.Repo.Migrations.AddStoryScriptView do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:story_script_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "story_script_views_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:story_script_views, [:story_id],
             name: "story_script_views_unique_story_index"
           )

    create table(:story_script_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false
      add :source_treatment_view_version_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_script_view_id,
          references(:story_script_views,
            column: :id,
            name: "story_script_view_versions_story_script_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:story_script_view_versions, [:story_script_view_id, :version_number],
             name: "story_script_view_versions_unique_version_per_view_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :story_script_view_versions,
                     [:story_script_view_id, :version_number],
                     name: "story_script_view_versions_unique_version_per_view_index"
                   )

    drop constraint(
           :story_script_view_versions,
           "story_script_view_versions_story_script_view_id_fkey"
         )

    drop table(:story_script_view_versions)

    drop_if_exists unique_index(:story_script_views, [:story_id],
                     name: "story_script_views_unique_story_index"
                   )

    drop constraint(:story_script_views, "story_script_views_story_id_fkey")

    drop table(:story_script_views)
  end
end
