defmodule Storybox.Repo.Migrations.AddSynopsisViewVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:synopsis_views) do
      remove :version_number
      remove :content_uri
    end

    # Dev DB may have multiple rows per story from the old append-only model.
    # Keep only the most recently inserted row per story before enforcing uniqueness.
    execute """
    DELETE FROM synopsis_views
    WHERE id NOT IN (
      SELECT DISTINCT ON (story_id) id
      FROM synopsis_views
      ORDER BY story_id, inserted_at DESC
    )
    """

    create unique_index(:synopsis_views, [:story_id], name: "synopsis_views_unique_story_index")

    create table(:synopsis_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :synopsis_view_id,
          references(:synopsis_views,
            column: :id,
            name: "synopsis_view_versions_synopsis_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:synopsis_view_versions, [:synopsis_view_id, :version_number],
             name: "synopsis_view_versions_unique_version_per_view_index"
           )
  end

  def down do
    drop_if_exists unique_index(:synopsis_view_versions, [:synopsis_view_id, :version_number],
                     name: "synopsis_view_versions_unique_version_per_view_index"
                   )

    drop constraint(:synopsis_view_versions, "synopsis_view_versions_synopsis_view_id_fkey")

    drop table(:synopsis_view_versions)

    drop_if_exists unique_index(:synopsis_views, [:story_id],
                     name: "synopsis_views_unique_story_index"
                   )

    alter table(:synopsis_views) do
      add :content_uri, :text, null: false
      add :version_number, :bigint, null: false
    end
  end
end
