defmodule Storybox.Repo.Migrations.AddSequenceView do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sequence_views, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :story_id,
          references(:stories,
            column: :id,
            name: "sequence_views_story_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sequence_id,
          references(:sequences,
            column: :id,
            name: "sequence_views_sequence_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:sequence_views, [:story_id, :sequence_id],
             name: "sequence_views_unique_per_story_sequence_index"
           )

    create table(:sequence_view_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sequence_view_id,
          references(:sequence_views,
            column: :id,
            name: "sequence_view_versions_sequence_view_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:sequence_view_versions, [:sequence_view_id, :version_number],
             name: "sequence_view_versions_unique_version_per_view_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sequence_view_versions, [:sequence_view_id, :version_number],
                     name: "sequence_view_versions_unique_version_per_view_index"
                   )

    drop constraint(:sequence_view_versions, "sequence_view_versions_sequence_view_id_fkey")

    drop table(:sequence_view_versions)

    drop_if_exists unique_index(:sequence_views, [:story_id, :sequence_id],
                     name: "sequence_views_unique_per_story_sequence_index"
                   )

    drop constraint(:sequence_views, "sequence_views_sequence_id_fkey")
    drop constraint(:sequence_views, "sequence_views_story_id_fkey")

    drop table(:sequence_views)
  end
end
