defmodule Storybox.Repo.Migrations.ScenePieceAndSceneVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scene_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content_uri, :text, null: false
      add :version_number, :bigint, null: false
      add :weights, :map, default: %{}
      add :upstream_status, :text, null: false, default: "current"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :scene_piece_id, :uuid, null: false
    end

    create table(:scene_pieces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:scene_versions) do
      modify :scene_piece_id,
             references(:scene_pieces,
               column: :id,
               name: "scene_versions_scene_piece_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:scene_pieces) do
      add :title, :text, null: false
      add :position, :bigint, null: false
      add :approved_version_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sequence_piece_id,
          references(:sequence_pieces,
            column: :id,
            name: "scene_pieces_sequence_piece_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:scene_pieces, "scene_pieces_sequence_piece_id_fkey")

    alter table(:scene_pieces) do
      remove :sequence_piece_id
      remove :updated_at
      remove :inserted_at
      remove :approved_version_id
      remove :position
      remove :title
    end

    drop constraint(:scene_versions, "scene_versions_scene_piece_id_fkey")

    alter table(:scene_versions) do
      modify :scene_piece_id, :uuid
    end

    drop table(:scene_pieces)

    drop table(:scene_versions)
  end
end
