defmodule Storybox.Repo.Migrations.DropSlotTreatmentView do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:treatment_pieces, "treatment_pieces_treatment_view_id_fkey")

    alter table(:treatment_pieces) do
      modify :treatment_view_id, :uuid
    end

    create index(:treatment_pieces, [:treatment_view_id])

    drop table(:treatment_view_scenes)
    drop table(:treatment_views)
  end

  def down do
    create table(:treatment_views, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :title, :text, null: false
      add :act, :text
      add :position, :integer, null: false
      add :approved_version_id, :uuid
      add :story_id, references(:stories, column: :id, type: :uuid, prefix: "public")
      timestamps()
    end

    create table(:treatment_view_scenes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :position, :integer, null: false

      add :treatment_view_id,
          references(:treatment_views, column: :id, type: :uuid, prefix: "public"),
          null: false

      add :scene_id, references(:scenes, column: :id, type: :uuid, prefix: "public"), null: false
      timestamps()
    end

    drop_if_exists index(:treatment_pieces, [:treatment_view_id])

    alter table(:treatment_pieces) do
      modify :treatment_view_id,
             references(:treatment_views,
               column: :id,
               name: "treatment_pieces_treatment_view_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
