defmodule Storybox.Repo.Migrations.CharacterSlug do
  @moduledoc """
  Adds a required, per-story-unique `slug` handle to Character.

  Hand-authored (rather than purely autogenerated) because backfill SQL must be
  interleaved with the schema changes: `slug` is added nullable, backfilled from
  `name` for any existing rows, and only then made NOT NULL. The matching
  resource snapshot is autogenerated.
  """

  use Ecto.Migration

  def up do
    # 1. Add slug (nullable first so existing rows can be backfilled).
    alter table(:characters) do
      add :slug, :text
    end

    # 2. Backfill slug from name, using underscores to match the existing seed
    #    slug convention (e.g. flame_demon). Dead path in practice — seed rows
    #    are recreated with authored slugs.
    execute "UPDATE characters SET slug = regexp_replace(lower(name), '[^a-z0-9]+', '_', 'g') WHERE slug IS NULL"

    # 3. Enforce slug NOT NULL now that every row has one.
    alter table(:characters) do
      modify :slug, :text, null: false
    end

    # 4. Unique slug per story.
    create unique_index(:characters, [:story_id, :slug],
             name: "characters_unique_slug_per_story_index"
           )
  end

  def down do
    drop_if_exists unique_index(:characters, [:story_id, :slug],
                     name: "characters_unique_slug_per_story_index"
                   )

    alter table(:characters) do
      remove :slug
    end
  end
end
